[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day9 = "3qxDkYTZTXcvXCwcaVWaQjFY74jv5tA9WEr8kUqDaEYK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anmol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
